language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - docker pull sameersbn/openfire:3.10.3-19
  - docker volume create jackal-openfire-datavolume
  - docker volume create -d local -o type=bind -o device=src/test/resources/openfire/ --name openfire
  - docker run -d -v openfire:/usr/lib/openfire -v jackal-openfire-datavolume:/var/openfire -p 127.0.0.1:5222:5222 sameersbn/openfire:3.10.3-19
  - docker ps -a

script:
  - mvn clean package verify

notifications:
  email:
    recipients:
      - josef.koch@gmail.com
    on_success: always # default: change
    on_failure: always # default: always