language: java

jdk:
  - oraclejdk8

script:
  - mvn clean verify package

notifications:
  email:
    recipients:
      - josef.koch@gmail.com
    on_success: always # default: change
    on_failure: always # default: always