version: "3"

services:

# see https://github.com/sameersbn/docker-openfire
  Openfire:
    image: ls
    ports:
      - "9090:9090"
      - "5222:5222"
      - "7777:7777"
    volumes:
      - jackal-openfire-datavolume:/var/openfire

volumes:
  jackal-openfire-datavolume: